const messages = {
  internalError: 'Internal error.',
  invalidParams: 'Invalid params',
  userAlreadyExist: 'This email is already in use',
  userAlreadyExist: 'This email is already in use',
  userRegisteredSuccessfully: 'User registered successfully',
  errorUserRegistered: 'Error registering user',
  userNotExistOrDeactivated: 'User does not exist or is deactivated',
  errorInLogin: 'Error in login',
  errorInUsersList: 'Error in getting users list',
  errorInUsersStatusChange: 'Error in changing user status',
  errorDeletingFile: 'Error deleting file',
  passwordOrEmailIsWrong: 'Password or email is wrong',
  loginSuccessFul: 'Login successful',
  unauthorized: 'You are not an authorized for this action',
  pleaseCheckAuth: 'Check auth token',
  allUsersFound: 'All users found',
  userStatusUpdated: 'User status updated',
  errorInUserUpdate: 'Error in user update',
  fileUploadedSuccessfully: 'File uploaded successfully',
  mediaNotFound: 'Document not found',
  mediaDeletedSuccessfully: 'Media deleted successfully',
  fileUploadFailed: 'File upload failed',
  errorFileUpload: 'Error in file upload',
  filesRetrievedSuccessfully: 'Files retrieved successfully',
  errorRetrievingFiles: 'Error retrieving files',
  errorDeletingMedia: 'Error deleting media',
  mediaUpdatedSuccessfully: 'Media updated successfully',
  errorUpdatingMedia: 'Error updating media',
};

module.exports = {
  messages,
};
